### ISSUE TITLE
[Feature Request] Taskbar icon status indicator - disable

### ISSUE THREAD

**Issue by nvirth** [sw3103/movemouse#63]
Please make the taskbar icon status indicator optional, because the yellow indication for the paused state - which is always the state when I'm using the computer - is very annoying.
It makes me learn to ignore when an icon prompts me with yellow color:

![image](https://github.com/sw3103/movemouse/assets/11088526/e26e8c88-9e92-406a-8ee6-14fb82c93210)

Thank you very much!

**Comment by sw3103** [comment]
Resolved in the 4.18.0 pre-release.

https://github.com/sw3103/movemouse/releases/tag/v4.18.0

Please test and give me your feedback.

**Comment by sw3103** [comment]
Reinstated as an option in the 4.18.2 release.

https://github.com/sw3103/movemouse/releases/tag/v4.18.2

**Comment by nvirth** [comment]
Sorry, somehow I missed your previous reply.
Thanks for the development, it works, I like it 🙂.

The only thing to mention is when I untick "Show status on taskbar", I have to restart the app to make it work. Until the restart, it still have some effect; because the color of the taskbar icon highlight is gone - but the progress (I mean the count down untill the next move) is still animated.

But that's not a problem for me, I restarted 😃
